version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DSN: ${APP_DSN}

    ports:
      - "8080:8080"


  db:
    image: postgres:alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: golang_project
